spring.application.name=taskapi

spring.profiles.active=dev

#Importar variables del .env
spring.config.import=optional:file:.env[.properties]

server.port=8085

#Configuracion del datasource usando las variables
# spring.datasource.url=jdbc:${SPRING_DATASOURCE_DRIVER}://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/${SPRING_DATASOURCE_DB}

spring.datasource.username=sa
spring.datasource.password=

# JPA
# Hibernate specific properties (optional, but commonly used with JPA)
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true 

# Optional: logs SQL queries to console
# spring.datasource.driver-class-name=org.postgresql.Driver


# H2
# Database connection settings
# spring.datasource.url=jdbc:h2:mem:taskapidb
spring.datasource.url=jdbc:h2:file:./data/taskapidb

spring.datasource.driver-class-name=org.h2.Driver

# Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 Web Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console