spring.application.name=taskapi

spring.profiles.active=dev

#Importar variables del .env
spring.config.import=optional:file:.env[.properties]

server.port=${APP_PORT}

#Configuracion del datasource usando las variables
spring.datasource.url=jdbc:${SPRING_DATASOURCE_DRIVER}://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/${SPRING_DATASOURCE_DB}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA
# Hibernate specific properties (optional, but commonly used with JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true 

# Optional: logs SQL queries to console
spring.datasource.driver-class-name=org.postgresql.Driver
